typography_spectrum: 0.5585021039005369
color:
  brandStrength: 0.6272306656464934
  lightness: 0.07057412038557231
  saturation: 0.5839092589449137
  rhythmicContrast: 0.8821239471435547
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#ACACAC'
    - '#535353'
    - '#6F2800'
layout_spectrum: 0.39159695827402174
name: THE SEO GRID
navigation:
  - name: Website Redesign Checklist - 10 Steps to Mitigate Loss of Rankings
    url: >-
      http://www.infront.com/blogs/the-infront-blog/2016/8/2/website-redesign-cheklist
    type: external
title: SEO
description: THE BEST OF SEO FROM AROUND THE WEB
